modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="halloween"
version="10.20.2020"
displayName="Halloween"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="JumpStartFartHam"

[[dependencies.halloween]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




